Update build.yml
Signed-off-by: Illia <75110249+Lolens@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,7 +5,6 @@ on:
     branches:
       - dev
       - main
-  workflow_dispatch: {}
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -18,6 +17,7 @@ jobs:
   info:
     name: 🖥️ Project Info
     runs-on: ubuntu-latest
+    if: ${{  github.repository_owner == 'TerraFirmaGreg-Team' }}
     outputs:
       project_version: ${{ steps.check.outputs.project_version }}
       project_name: ${{ steps.check.outputs.project_name }}
@@ -28,8 +28,9 @@ jobs:
       loader_type: ${{ steps.check.outputs.loader_type }}
       release_type: ${{ steps.check.outputs.release_type }}
       diff: ${{ steps.read_diff.outputs.diff }}
-      exists: ${{ steps.check.outputs.exists }}
+      exists: ${{ steps.check_tag.outputs.exists }}
       make_release: ${{ steps.check.outputs.make_release }}
+      make_pr: ${{ steps.check.outputs.make_pr }}
     
     steps:
       - name: 📦 Checkout
@@ -61,20 +62,12 @@ jobs:
         id: latest_tag
         shell: bash
         run: |
-          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
-            TAG_VERSION="${GITHUB_REF#refs/tags/}"
-            echo "✔️ Using trigger tag: $TAG_VERSION"
-            echo "tag=$TAG_VERSION" >> $GITHUB_OUTPUT
-            echo "tag_source=trigger" >> $GITHUB_OUTPUT
+          tag=$(git describe --tags --abbrev=0 origin/main)
+          if [ -z "$tag" ]; then
+            echo "❌ Latest tag not found" && exit 1
           else
-            tag=$(git describe --tags --abbrev=0 origin/main 2>/dev/null || echo "")
-            if [ -z "$tag" ]; then
-              echo "❌ Latest tag not found" && exit 1
-            else
-              echo "✔️ Latest tag found: $tag"
-              echo "tag=$tag" >> $GITHUB_OUTPUT
-              echo "tag_source=git_describe" >> $GITHUB_OUTPUT
-            fi
+            echo "✔️ Latest tag found: $tag"
+            echo "tag=$tag" >> $GITHUB_OUTPUT
           fi
         
       - name: 🔍 Check pakku-lock.json in previous tag
@@ -91,7 +84,7 @@ jobs:
         
       - name: 📁 Check and copy pakku-lock.json from previous tag
         id: check_copy_lock
-        if: steps.check_pakku_lock_prev.outputs.file_found
+        if: steps.check_pakku_lock_prev.outputs.file_found == 'true'
         shell: bash
         run: |
           git show tags/${{ steps.latest_tag.outputs.tag }}:./pakku-lock.json > ./pakku-lock-prev.json
@@ -101,17 +94,9 @@ jobs:
             echo "❌ Error: File pakku-lock-prev.json is empty or not created" && exit 1
           fi
         
-      # - name: 📦 Download pakku.jar
-      #   id: download_pakku
-      #   if: steps.check_pakku_lock_prev.outputs.file_found
-      #   shell: bash
-      #   run: |
-      #     curl https://github.com/juraj-hrivnak/pakku/releases/latest/download/pakku.jar -o pakku.jar -L -J
-      #     echo "✔️ Downloaded pakku.jar "
-        
       - name: 🔄 Run pakku diff
         id: pakku_diff
-        if: steps.check_pakku_lock_prev.outputs.file_found
+        if: steps.check_pakku_lock_prev.outputs.file_found == 'true'
         shell: bash
         run: |
           java -jar pakku.jar diff -v --markdown PROJECTS_DIFF.md ./pakku-lock-prev.json ./pakku-lock.json
@@ -123,7 +108,7 @@ jobs:
         
       - name: 📝 Read PROJECTS_DIFF.md to variable
         id: read_diff
-        if: steps.check_pakku_lock_prev.outputs.file_found
+        if: steps.check_pakku_lock_prev.outputs.file_found == 'true'
         shell: bash
         run: |
           echo "📝 Reading PROJECTS_DIFF.md to variable..."
@@ -166,36 +151,36 @@ jobs:
         uses: mukunku/tag-exists-action@v1.7.0
         id: check_tag
         with:
-          tag: ${{ steps.latest_tag.outputs.tag }}
+          tag: ${{ steps.changelog.outputs.version }}
 
       - name: 🔍 Check
         id: check
         shell: bash
         run: |
+         
           MC_VERSIONS_JSON='${{ steps.pakku_lock_info.outputs.mc_versions }}'
           MINECRAFT_VERSION=$(echo "$MC_VERSIONS_JSON" | jq -r '.[0]' | tr -d '[]"')
 
           LOADERS_JSON='${{ steps.pakku_lock_info.outputs.loaders }}'
+
           LOADER_TYPE=$(echo "$LOADERS_JSON" | jq -r 'keys[0]')
           LOADER_VERSION=$(echo "$LOADERS_JSON" | jq -r ".[keys[0]]")
 
           echo "minecraft_version=$MINECRAFT_VERSION" >> $GITHUB_OUTPUT
           echo "loader_version=$LOADER_VERSION" >> $GITHUB_OUTPUT
           echo "loader_type=$LOADER_TYPE" >> $GITHUB_OUTPUT
-          echo "project_name=${{ steps.pakku_info.outputs.name }}" >> $GITHUB_OUTPUT
-          echo "release_type=${{ steps.pakku_info.outputs.release_type }}" >> $GITHUB_OUTPUT
 
           if ${{ env.DEV_ENVIRONMENT == 'true' }}; then
             echo "project_version=build_#${{ github.run_number }}" >> $GITHUB_OUTPUT
           else
-            echo "project_version=${{ steps.latest_tag.outputs.tag }}" >> $GITHUB_OUTPUT
+            echo "project_version=${{ steps.changelog.outputs.version }}" >> $GITHUB_OUTPUT
           fi
 
-          echo "exists=${{ steps.check_tag.outputs.exists }}" >> $GITHUB_OUTPUT
-          
-          MAKE_RELEASE=${{ env.DEV_ENVIRONMENT == 'false' && steps.check_tag.outputs.exists == 'false' && github.ref_name == 'main' }}
-          echo "make_release=$MAKE_RELEASE" >> $GITHUB_OUTPUT
-      
+          echo "project_name=${{ steps.pakku_info.outputs.name }}" >> $GITHUB_OUTPUT
+          echo "release_type=${{ steps.pakku_info.outputs.release_type }}" >> $GITHUB_OUTPUT
+          echo "make_release=${{ steps.check_tag.outputs.exists == 'false' && env.DEV_ENVIRONMENT == 'false' }}" >> $GITHUB_OUTPUT
+          echo "make_pr=${{ steps.check_tag.outputs.exists == 'false' && env.DEV_ENVIRONMENT == 'true' }}" >> $GITHUB_OUTPUT
+
       - name: 📄 Format diff
         id: format_diff
         if: ${{ steps.read_diff.outputs.diff != '' }}
@@ -212,19 +197,106 @@ jobs:
           template: |
             📃 **Name**: ${{ steps.check.outputs.project_name }}
             📃 **Release**:  `${{ steps.check.outputs.project_version }}`
-            📃 **Tag Source**: `${{ steps.latest_tag.outputs.tag_source }}`
             📃 **Release Type**: `${{ steps.check.outputs.release_type }}`
             📃 **Game Version**: `${{ steps.check.outputs.minecraft_version }}`
             📃 **Loader Type**: `${{ steps.check.outputs.loader_type }}`
             📃 **Loader Version**: `${{ steps.check.outputs.loader_version }}`
 
             📃 **Dev Environment**: `${{ env.DEV_ENVIRONMENT }}`
-            📃 **Tag Exists**: `${{ steps.check.outputs.exists }}`
+            📃 **Tag Exists**: `${{ steps.check_tag.outputs.exists }}`
+            📃 **Make Pull Request**: `${{ steps.check.outputs.make_pr }}`
             📃 **Make Release**: `${{ steps.check.outputs.make_release }}`
             
-            ${{ steps.changelog.outputs.description }}
+
+            ${{ steps.changelog_dev.outputs.description }}
             ${{ steps.format_diff.outputs.text }}
   
+  create-pr:
+    name: 🤝 Create Release PR
+    needs: [info]
+    if: ${{ needs.info.outputs.make_pr == 'true' }}
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Checkout
+        uses: actions/checkout@v6.0.1
+        with:
+          fetch-depth: 0
+
+      - name: 📄 Changelog Parser
+        id: changelog
+        uses: coditory/changelog-parser@v1.0.2
+        with:
+          path: CHANGELOG.md
+        continue-on-error: true
+
+      - name: 🔍 Check existing PRs
+        id: check_existing_pr
+        uses: actions/github-script@v8.0.0
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          result-encoding: string
+          script: |
+            try {
+              const { data: prs } = await github.rest.pulls.list({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                state: 'open',
+                head: `${context.repo.owner}:dev`,
+                base: 'main'
+              });
+
+              core.setOutput('exists', prs.length > 0);
+              console.log(`ℹ️ PR exists: ${prs.length > 0}`);
+            } catch (error) {
+              core.setFailed(`❌ PR check failed: ${error}`);
+              core.setOutput('exists', true);
+            }
+
+      - name: 🔍 Check if milestone exists
+        id: check_milestone
+        uses: actions/github-script@v8.0.0
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          result-encoding: string
+          script: |
+            const version = '${{ steps.changelog.outputs.version }}';
+            try {
+              const milestones = await github.rest.issues.listMilestones({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                state: 'all'
+              });
+              const milestoneExists = milestones.data.some(milestone => milestone.title === version);
+              console.log(`Milestone "${version}" exists: ${milestoneExists}`);
+              return milestoneExists;
+            } catch (error) {
+              console.log('Error checking milestones, assuming milestone does not exist');
+              return false;
+            }
+
+      - name: 🔍 Create Pull Request if tag not found
+        if: ${{ steps.check_existing_pr.outputs.exists == 'false' }}
+        uses: devops-infra/action-pull-request@v1.0.2
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          source_branch: dev
+          target_branch: main
+          milestone: ${{ steps.check_milestone.outputs.result == 'true' && steps.changelog.outputs.version || '' }}
+          ignore_users: "dependabot"
+          draft: true
+          title: 'Release: ${{ steps.changelog.outputs.version }}'
+          body: |
+            **This is an automated Pull Request from the dev branch.**
+            📃 **Name**: ${{ needs.info.outputs.project_name }}
+            📃 **Release**:  `${{ steps.changelog.outputs.version }}`
+            📃 **Release Type**: `${{ needs.info.outputs.release_type }}`
+            📃 **Loader**: `${{ needs.info.outputs.loader_type }}-${{ needs.info.outputs.loader_version }}`
+
+            ${{ needs.info.outputs.changelog }}
+
   build-project:
     name: 📦 Build Project
     needs: [info]
@@ -242,7 +314,6 @@ jobs:
           LOADER_VERSION=${{ needs.info.outputs.loader_version }}
           LOADER_TYPE=${{ needs.info.outputs.loader_type }}
           MINECRAFT_VERSION=${{ needs.info.outputs.mc_version }}
-
 
           sed -i -e "s/DEV/${VERSION}/g" pakku.json
           sed -i -e "s/DEV/${VERSION}/g" config/mod-director/modpack.json
@@ -267,44 +338,18 @@ jobs:
 
       - name: 📦 Export modpack
         run: |
-          # curl https://github.com/juraj-hrivnak/pakku/releases/latest/download/pakku.jar -o pakku.jar -L -J
           java -jar pakku.jar fetch
           java -jar pakku.jar export
 
           mkdir -p .pakku/multimc-overrides/flame
           mkdir -p .pakku/multimc-overrides/mods
 
-      - name: 📁 Preparing the artifact curseforge
-        run: |
-          cd ./build/curseforge/
-          mv *.zip $(basename -s .zip *.zip)-curseforge.zip
-          
-      - name: 🚀 Upload artifact CurseForge
-        uses: actions/upload-artifact@v6.0.0
-        with:
-          name: ${{ needs.info.outputs.project_full_name }}-curseforge
-          path: ./build/curseforge/${{ needs.info.outputs.project_full_name }}-curseforge.zip
-          if-no-files-found: error
-
-      - name: 📁 Preparing the artifact modrinth
-        run: |
-          cd ./build/modrinth/
-          mv *.mrpack $(basename -s .mrpack *.mrpack)-modrinth.mrpack
-
-      - name: 🚀 Upload artifact modrinth
-        uses: actions/upload-artifact@v6.0.0
-        with:
-          name: ${{ needs.info.outputs.project_full_name }}-modrinth
-          path: ./build/modrinth/${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
-          if-no-files-found: warn
-
       - name: 📁 Preparing the artifact multimc
         run: |
           mkdir -p .pakku/multimc-overrides/flame
           mkdir -p .pakku/multimc-overrides/mods
 
-          mv -vf .pakku/multimc-overrides ./build/multimc
-
+          mv -vf .pakku/multimc-overrides ./build/multimc/
           
           cp -rf ./build/.cache/curseforge/overrides ./build/multimc/.minecraft
 
@@ -355,12 +400,6 @@ jobs:
         id: check_artifact
         shell: bash
         run: |
-          if [ ! -f ${{ needs.info.outputs.project_full_name }}-curseforge.zip ]; then
-            echo '::error::No value found for artifact `curseforge.zip`.' && exit 1
-          fi
-          # if [ ! -f ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack ]; then
-          #   echo '::error::No value found for artifact `modrinth.mrpack`.' && exit 1
-          # fi
           if [ ! -f ${{ needs.info.outputs.project_full_name }}-serverpack.zip ]; then
             echo '::error::No value found for artifact `serverpack.zip`.' && exit 1
           fi
@@ -390,8 +429,6 @@ jobs:
             ${{ needs.info.outputs.changelog }}
             ${{ steps.format_diff.outputs.text }}
           files: |
-            ${{ needs.info.outputs.project_full_name }}-curseforge.zip
-            ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
             ${{ needs.info.outputs.project_full_name }}-serverpack.zip
             ${{ needs.info.outputs.project_full_name }}-multimc.zip
           prerelease: ${{ needs.info.outputs.release_type != 'release' }}
